//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductView
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int guest_id { get; set; }
        public System.DateTime view_date { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Product Product { get; set; }
    }
}
